sbatch ./ars/ars_LunarLanderContinuous.sl
sbatch ./ars/ars_Walker2D.sl
sbatch ./ars/ars_InvertedPendulum.sl
sbatch ./ars/ars_InvertedPendulumSwingup.sl
sbatch ./ars/ars_Hopper.sl
sbatch ./ars/ars_InvertedDoublePendulum.sl
sbatch ./ars/ars_MountainCarContinuous.sl
sbatch ./ars/ars_BipedalWalker.sl
sbatch ./ppo_linear/ppo_linear_InvertedDoublePendulum.sl
sbatch ./ppo_linear/ppo_linear_MountainCarContinuous.sl
sbatch ./ppo_linear/ppo_linear_InvertedPendulum.sl
sbatch ./ppo_linear/ppo_linear_InvertedPendulumSwingup.sl
sbatch ./ppo_linear/ppo_linear_Walker2D.sl
sbatch ./ppo_linear/ppo_linear_Hopper.sl
sbatch ./ppo_linear/ppo_linear_BipedalWalker.sl
sbatch ./ppo_linear/ppo_linear_LunarLanderContinuous.sl