sbatch ./ars/ars_LunarLanderContinuous.sl
sbatch ./ars/ars_Walker2D.sl
sbatch ./ars/ars_InvertedPendulum.sl
sbatch ./ars/ars_InvertedPendulumSwingup.sl
sbatch ./ars/ars_Hopper.sl
sbatch ./ars/ars_InvertedDoublePendulum.sl
sbatch ./ars/ars_MountainCarContinuous.sl
sbatch ./ars/ars_BipedalWalker.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_InvertedPendulum.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_MountainCarContinuous.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_InvertedPendulumSwingup.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_Walker2D.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_InvertedDoublePendulum.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_Hopper.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_LunarLanderContinuous.sl
sbatch ./dual_nac_advantage/dual_nac_advantage_BipedalWalker.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_LunarLanderContinuous.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_Hopper.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_Walker2D.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_InvertedPendulum.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_InvertedDoublePendulum.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_InvertedPendulumSwingup.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_MountainCarContinuous.sl
sbatch ./dual_nac_fisher/dual_nac_fisher_BipedalWalker.sl
sbatch ./dual_rac/dual_rac_InvertedDoublePendulum.sl
sbatch ./dual_rac/dual_rac_InvertedPendulumSwingup.sl
sbatch ./dual_rac/dual_rac_InvertedPendulum.sl
sbatch ./dual_rac/dual_rac_MountainCarContinuous.sl
sbatch ./dual_rac/dual_rac_BipedalWalker.sl
sbatch ./dual_rac/dual_rac_Walker2D.sl
sbatch ./dual_rac/dual_rac_Hopper.sl
sbatch ./dual_rac/dual_rac_LunarLanderContinuous.sl