#! /bin/bash
bash dual_nac_advantage_MountainCarContinuous.sh
bash dual_nac_advantage_InvertedDoublePendulum.sh
bash dual_nac_advantage_InvertedPendulum.sh
bash dual_nac_advantage_InvertedPendulumSwingup.sh
bash dual_nac_advantage_BipedalWalker.sh
bash dual_nac_advantage_LunarLanderContinuous.sh





