#! /bin/bash
nac_advantage_fisher_HalfCheetah.sh
nac_advantage_fisher_Hopper.sh
nac_advantage_fisher_InvertedDoublePendulum.sh
nac_advantage_fisher_InvertedPendulum.sh
nac_advantage_fisher_InvertedPendulumSwingup.sh
nac_advantage_fisher_Reacher.sh
nac_advantage_fisher_Walker2D.sh
nac_advantage_fisher_BipedalWalker.sh
nac_advantage_fisher_BipedalWalkerHardcore.sh
nac_advantage_fisher_LunarLanderContinuous.sh





