#! /bin/bash
bash nac_advantage_fisher_MountainCarContinuous.sh
bash nac_advantage_fisher_InvertedDoublePendulum.sh
bash nac_advantage_fisher_InvertedPendulum.sh
bash nac_advantage_fisher_InvertedPendulumSwingup.sh
bash nac_advantage_fisher_BipedalWalker.sh
bash nac_advantage_fisher_LunarLanderContinuous.sh





