qsub -t 1-15:1 ./ars/ars_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./ars/ars_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./ars/ars_Hopper.sh
qsub -t 1-15:1 ./ars/ars_Walker2D.sh
qsub -t 1-15:1 ./ars/ars_InvertedPendulum.sh
qsub -t 1-15:1 ./ars/ars_MountainCarContinuous.sh
qsub -t 1-15:1 ./ars/ars_BipedalWalker.sh
qsub -t 1-15:1 ./ars/ars_Reacher.sh
qsub -t 1-15:1 ./ars/ars_LunarLanderContinuous.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_Hopper.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_LunarLanderContinuous.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_Reacher.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_BipedalWalker.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_InvertedPendulum.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_MountainCarContinuous.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_Walker2D.sh
qsub -t 1-15:1 ./dual_nac_advantage/dual_nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_InvertedPendulum.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_Reacher.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_MountainCarContinuous.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_BipedalWalker.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_LunarLanderContinuous.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_Hopper.sh
qsub -t 1-15:1 ./dual_nac_fisher/dual_nac_fisher_Walker2D.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_Walker2D.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_Hopper.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_LunarLanderContinuous.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_Reacher.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_InvertedPendulum.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_MountainCarContinuous.sh
qsub -t 1-15:1 ./dual_rac/dual_rac_BipedalWalker.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_BipedalWalker.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_LunarLanderContinuous.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_Hopper.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_Walker2D.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_Reacher.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_MountainCarContinuous.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./nac_advantage/nac_advantage_InvertedPendulum.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_Walker2D.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_Reacher.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_Hopper.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedPendulum.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_LunarLanderContinuous.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_MountainCarContinuous.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./nac_advantage_fisher/nac_advantage_fisher_BipedalWalker.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_Hopper.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_LunarLanderContinuous.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_Reacher.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_InvertedPendulum.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_BipedalWalker.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_Walker2D.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_MountainCarContinuous.sh
qsub -t 1-15:1 ./nac_fisher/nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_Reacher.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_Hopper.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_BipedalWalker.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_Walker2D.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_LunarLanderContinuous.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_MountainCarContinuous.sh
qsub -t 1-15:1 ./ppo_linear/ppo_linear_InvertedPendulum.sh
qsub -t 1-15:1 ./rac/rac_LunarLanderContinuous.sh
qsub -t 1-15:1 ./rac/rac_Reacher.sh
qsub -t 1-15:1 ./rac/rac_InvertedDoublePendulum.sh
qsub -t 1-15:1 ./rac/rac_BipedalWalker.sh
qsub -t 1-15:1 ./rac/rac_Walker2D.sh
qsub -t 1-15:1 ./rac/rac_Hopper.sh
qsub -t 1-15:1 ./rac/rac_InvertedPendulumSwingup.sh
qsub -t 1-15:1 ./rac/rac_InvertedPendulum.sh
qsub -t 1-15:1 ./rac/rac_MountainCarContinuous.sh