qsub -t 1-5:1 ./ars/ars_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ars/ars_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ars/ars_InvertedPendulum.sh
qsub -t 1-5:1 ./ars/ars_MountainCarContinuous.sh
qsub -t 1-5:1 ./dual_nac_advantage/dual_nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./dual_nac_advantage/dual_nac_advantage_InvertedPendulum.sh
qsub -t 1-5:1 ./dual_nac_advantage/dual_nac_advantage_MountainCarContinuous.sh
qsub -t 1-5:1 ./dual_nac_advantage/dual_nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./dual_nac_fisher/dual_nac_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./dual_nac_fisher/dual_nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./dual_nac_fisher/dual_nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./dual_nac_fisher/dual_nac_fisher_MountainCarContinuous.sh
qsub -t 1-5:1 ./dual_rac/dual_rac_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./dual_rac/dual_rac_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./dual_rac/dual_rac_InvertedPendulum.sh
qsub -t 1-5:1 ./dual_rac/dual_rac_MountainCarContinuous.sh
qsub -t 1-5:1 ./nac_advantage/nac_advantage_MountainCarContinuous.sh
qsub -t 1-5:1 ./nac_advantage/nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./nac_advantage/nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./nac_advantage/nac_advantage_InvertedPendulum.sh
qsub -t 1-5:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./nac_advantage_fisher/nac_advantage_fisher_MountainCarContinuous.sh
qsub -t 1-5:1 ./nac_advantage_fisher/nac_advantage_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./nac_fisher/nac_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./nac_fisher/nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./nac_fisher/nac_fisher_MountainCarContinuous.sh
qsub -t 1-5:1 ./nac_fisher/nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_linear/ppo_linear_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_linear/ppo_linear_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_linear/ppo_linear_MountainCarContinuous.sh
qsub -t 1-5:1 ./ppo_linear/ppo_linear_InvertedPendulum.sh
qsub -t 1-5:1 ./rac/rac_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./rac/rac_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./rac/rac_InvertedPendulum.sh
qsub -t 1-5:1 ./rac/rac_MountainCarContinuous.sh