qsub -t 1-5:1 ./ppo/ppo_HalfCheetah.sh
qsub -t 1-5:1 ./ppo/ppo_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo/ppo_Hopper.sh
qsub -t 1-5:1 ./ppo/ppo_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo/ppo_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo/ppo_BipedalWalker.sh
qsub -t 1-5:1 ./ppo/ppo_Reacher.sh
qsub -t 1-5:1 ./ppo/ppo_Walker2D.sh
qsub -t 1-5:1 ./ppo/ppo_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo/ppo_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_Reacher.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_Hopper.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_Walker2D.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_rac/ppo_rac_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_Reacher.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_Hopper.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_Walker2D.sh
qsub -t 1-5:1 ./ppo_nac_fisher/ppo_nac_fisher_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_Reacher.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_Walker2D.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_Hopper.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_nac_advantage_fisher/ppo_nac_advantage_fisher_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_Hopper.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_Walker2D.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_Reacher.sh
qsub -t 1-5:1 ./ppo_nac_advantage/ppo_nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_Reacher.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_Walker2D.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_Hopper.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_dual_rac/ppo_dual_rac_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_Reacher.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_Walker2D.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_Hopper.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_dual_nac_fisher/ppo_dual_nac_fisher_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_BipedalWalkerHardcore.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_BipedalWalker.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_LunarLanderContinuous.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_InvertedPendulumSwingup.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_Hopper.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_HalfCheetah.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_InvertedDoublePendulum.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_Reacher.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_InvertedPendulum.sh
qsub -t 1-5:1 ./ppo_dual_nac_advantage/ppo_dual_nac_advantage_Walker2D.sh